### ISSUE TITLE
ERROR --> Invalid user id. - 0

### ISSUE THREAD

**Issue by GregLeonhardt** [ryanhowdy/fcms#624] opened 2021-07-16 19:37 UTC
When displaying the 'Home' page and there is a new poll the following error will be generated.

2021-07-16 13:23:58 - ERROR --> Invalid user id. - 0
  FILE  - /var/www/html/fcms_archive/inc/utils.php [157]
  PHP   - 7.0.33-0+deb9u10 (Linux)
  STACK
    #0 __construct called at [/var/www/html/fcms_archive/home.php:40]
    #1 control called at [/var/www/html/fcms_archive/home.php:69]
    #2 displayWhatsNew called at [/var/www/html/fcms_archive/home.php:94]
    #3 displayWhatsNewAll called at [/var/www/html/fcms_archive/home.php:276]
    #4 getUserDisplayName called at [/var/www/html/fcms_archive/home.php:599]
    #5 add called at [/var/www/html/fcms_archive/inc/utils.php:153]

I believe the root cause of the above error is the lack of a user associated with a poll.

**Comment by ryanhowdy** [comment] 2021-07-16 19:52
This is a duplicate of Issue #612 and has already been fixed in the 3.8 branch.

**Closed by ryanhowdy** 2021-07-16 19:52 UTC
