### ISSUE TITLE
Install - Error during installation process

### ISSUE THREAD

**Issue by Skyturtle** [ryanhowdy/fcms#558] opened 2018-01-23 20:22 UTC
I tried an installation of fcms-3.7.0 in XAMPP of version 7.2.1 / PHP 7.2.1 (Windows 32-bit). While the installation process the following error is occurred: "Fatal error: Cannot redeclare ImageCreateFromBMP() in \path_to\fcms-3.7.0\familyconnections\inc\utils.php on line 3647".

**Comment by ryanhowdy** [comment] 2018-12-06 02:52
This is a duplicate of #565 .

**Closed by ryanhowdy** 2018-12-06 02:52 UTC
Labels: Critical
